spring:
  data:
    redis:
      repositories:
        enabled: false

  application:
    name: shopping-cart

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      uri: http://localhost:8888