spring:
  data:
    elasticsearch:
      repositories:
        enabled: true

  application:
    name: product-catalog

  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      uri: http://localhost:8888
