server:
  port:
    8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LeiteSS/microservices-config.git
          username: LeiteSS
          password: 03568799We
